.\"                                      Hey, EMACS: -*- nroff -*-
.TH ALB_XML2SEXP 1 "July 4, 2003"
.SH NAME
alb_xml2sexp \- Albert's XML to symbolic-expression converter
.SH SYNOPSIS
.B alb_xml2sexp [OPTIONS] input-file output-file
.SH DESCRIPTION
.B alb_xml2sexp
is used by the albert library as a helper to convert XML
into symbolic-expressions.
